### ISSUE TITLE
Can't login via facebook

### ISSUE THREAD

**Issue by tinhien11** [mysteryjeans/codehunkit#1]
I had message when login via facebook "We encounter some error while logging you in through Facebook". I think facebook api v1 outdated

**Comment by mysteryjeans** [comment]
It seems Facebook has removed username from graph API v2.0, and currently there is noway to obtain it. It is mentioned in [changelog](https://developers.facebook.com/docs/apps/changelog#v2_0_graph_api), here is the link to [graph /user reference](https://developers.facebook.com/docs/graph-api/reference/user)
